feeds:
    - url: https://without.boats/index.xml
      name: without.boats
    - url: https://blog.qassim.uk/rss/
      name: Qassim
    - url: https://overreacted.io/rss.xml
      name: Dan Abramov
