import = [
    "~/.config/alacritty/themes/themes/gruvbox_material.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[shell]
args = ["new-session", "-A", "-s", "main"]
program = "/opt/homebrew/bin/tmux"
